apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/mydata
            name: my-data-pv
#      nodeSelector: 
      volumes:
        - name: my-data-pv
          persistentVolumeClaim:
            claimName: testing-pvc-az 
