apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testing-pvc-az 
spec:
  storageClassName: apollo-sc
  resources:
    requests:
      storage: 5M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce


